-- Migration 006: Import 24 real Save the Date designs from PDFs
-- Auto-generated by scripts/process-designs.py


INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Autumn', 'autumn', 'Announce your wedding with our stunning Autumn save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,traditional}', '{terracotta,burgundy}',
  true, 100,
  '/designs/autumn/product.png',
  ARRAY['/designs/autumn/preview.png', '/designs/autumn/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Blue Roses', 'blue-roses', 'Announce your wedding with our stunning Blue Roses save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,romantic}', '{blues,pinks}',
  true, 101,
  '/designs/blue-roses/product.png',
  ARRAY['/designs/blue-roses/preview.png', '/designs/blue-roses/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Blush Floral 2', 'blush-floral-2', 'Announce your wedding with our stunning Blush Floral 2 save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,romantic}', '{pinks,neutrals}',
  true, 102,
  '/designs/blush-floral-2/product.png',
  ARRAY['/designs/blush-floral-2/preview.png', '/designs/blush-floral-2/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Blush Floral', 'blush-floral', 'Announce your wedding with our stunning Blush Floral save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,romantic}', '{pinks,neutrals}',
  true, 103,
  '/designs/blush-floral/product.png',
  ARRAY['/designs/blush-floral/preview.png', '/designs/blush-floral/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Bouquet', 'bouquet', 'Announce your wedding with our stunning Bouquet save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,traditional}', '{pinks,greens}',
  true, 104,
  '/designs/bouquet/product.png',
  ARRAY['/designs/bouquet/preview.png', '/designs/bouquet/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Calligraphy', 'calligraphy', 'Announce your wedding with our stunning Calligraphy save the date cards, with timeless, classic design details. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{traditional,romantic}', '{neutrals}',
  true, 105,
  '/designs/calligraphy/product.png',
  ARRAY['/designs/calligraphy/preview.png', '/designs/calligraphy/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Confetti', 'confetti', 'Announce your wedding with our stunning Confetti save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{pinks,gold}',
  true, 106,
  '/designs/confetti/product.png',
  ARRAY['/designs/confetti/preview.png', '/designs/confetti/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Delicate', 'delicate', 'Announce your wedding with our stunning Delicate save the date cards, with an elegant, pared-back aesthetic. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{minimal,romantic}', '{neutrals,pinks}',
  true, 107,
  '/designs/delicate/product.png',
  ARRAY['/designs/delicate/preview.png', '/designs/delicate/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Destination', 'destination', 'Announce your wedding with our stunning Destination save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{neutrals,blues}',
  true, 108,
  '/designs/destination/product.png',
  ARRAY['/designs/destination/preview.png', '/designs/destination/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Eucalyptus', 'eucalyptus', 'Announce your wedding with our stunning Eucalyptus save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,minimal}', '{greens,neutrals}',
  true, 109,
  '/designs/eucalyptus/product.png',
  ARRAY['/designs/eucalyptus/preview.png', '/designs/eucalyptus/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Fiery', 'fiery', 'Announce your wedding with our stunning Fiery save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{terracotta,burgundy}',
  true, 110,
  '/designs/fiery/product.png',
  ARRAY['/designs/fiery/preview.png', '/designs/fiery/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Green Leaves Watercolour', 'green-leaves-watercolour', 'Announce your wedding with our stunning Green Leaves Watercolour save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical}', '{greens}',
  true, 111,
  '/designs/green-leaves-watercolour/product.png',
  ARRAY['/designs/green-leaves-watercolour/preview.png', '/designs/green-leaves-watercolour/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Gypsophila Save the Date', 'gypsophila-save-the-date', 'Announce your wedding with our stunning Gypsophila Save the Date save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,romantic}', '{neutrals,greens}',
  true, 112,
  '/designs/gypsophila-save-the-date/product.png',
  ARRAY['/designs/gypsophila-save-the-date/preview.png', '/designs/gypsophila-save-the-date/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Kraft', 'kraft', 'Announce your wedding with our stunning Kraft save the date cards, with an elegant, pared-back aesthetic. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{minimal,traditional}', '{neutrals}',
  true, 113,
  '/designs/kraft/product.png',
  ARRAY['/designs/kraft/preview.png', '/designs/kraft/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Lavender', 'lavender', 'Announce your wedding with our stunning Lavender save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,romantic}', '{purples,greens}',
  true, 114,
  '/designs/lavender/product.png',
  ARRAY['/designs/lavender/preview.png', '/designs/lavender/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Movie', 'movie', 'Announce your wedding with our stunning Movie save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{neutrals}',
  true, 115,
  '/designs/movie/product.png',
  ARRAY['/designs/movie/preview.png', '/designs/movie/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Mr & Mr', 'mr-mr', 'Announce your wedding with our stunning Mr & Mr save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{neutrals}',
  true, 116,
  '/designs/mr-mr/product.png',
  ARRAY['/designs/mr-mr/preview.png', '/designs/mr-mr/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Mushroom', 'mushroom', 'Announce your wedding with our stunning Mushroom save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical}', '{neutrals,terracotta}',
  true, 117,
  '/designs/mushroom/product.png',
  ARRAY['/designs/mushroom/preview.png', '/designs/mushroom/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'October', 'october', 'Announce your wedding with our stunning October save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,traditional}', '{burgundy,terracotta}',
  true, 118,
  '/designs/october/product.png',
  ARRAY['/designs/october/preview.png', '/designs/october/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Old Sunflowers', 'old-sunflowers', 'Announce your wedding with our stunning Old Sunflowers save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,traditional}', '{gold,greens}',
  true, 119,
  '/designs/old-sunflowers/product.png',
  ARRAY['/designs/old-sunflowers/preview.png', '/designs/old-sunflowers/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Olive', 'olive', 'Announce your wedding with our stunning Olive save the date cards, adorned with hand-painted botanical illustrations. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{botanical,minimal}', '{greens,neutrals}',
  true, 120,
  '/designs/olive/product.png',
  ARRAY['/designs/olive/preview.png', '/designs/olive/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Outlines', 'outlines', 'Announce your wedding with our stunning Outlines save the date cards, with an elegant, pared-back aesthetic. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{minimal,modern}', '{neutrals}',
  true, 121,
  '/designs/outlines/product.png',
  ARRAY['/designs/outlines/preview.png', '/designs/outlines/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Rust', 'rust', 'Announce your wedding with our stunning Rust save the date cards, with clean, contemporary styling. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{modern}', '{terracotta}',
  true, 122,
  '/designs/rust/product.png',
  ARRAY['/designs/rust/preview.png', '/designs/rust/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;

INSERT INTO design_collections (name, slug, description, style_tags, colour_tags, is_published, sort_order, hero_image_url, preview_images)
VALUES (
  'Whimsical', 'whimsical', 'Announce your wedding with our stunning Whimsical save the date cards, featuring flowing, romantic design elements. Personalise with your names, date and venue for a design that''s uniquely yours. Printed on premium 350gsm card stock with a luxurious finish.',
  '{romantic,botanical}', '{pinks,purples}',
  true, 123,
  '/designs/whimsical/product.png',
  ARRAY['/designs/whimsical/preview.png', '/designs/whimsical/thumbnail.png']
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  style_tags = EXCLUDED.style_tags, colour_tags = EXCLUDED.colour_tags,
  is_published = true, hero_image_url = EXCLUDED.hero_image_url,
  preview_images = EXCLUDED.preview_images;


-- Link each collection to save-the-dates template and create storefront products
DO $$
DECLARE
  coll RECORD;
  std_template_id UUID;
  pt_id UUID;
  cp_id UUID;
  p_slug TEXT;
  p_name TEXT;
BEGIN
  SELECT id INTO std_template_id FROM design_templates WHERE slug = 'save-the-dates' LIMIT 1;
  SELECT id INTO pt_id FROM product_types WHERE slug = 'save-the-dates' LIMIT 1;

  FOR coll IN SELECT id, name, slug FROM design_collections WHERE slug IN ('autumn', 'blue-roses', 'blush-floral-2', 'blush-floral', 'bouquet', 'calligraphy', 'confetti', 'delicate', 'destination', 'eucalyptus', 'fiery', 'green-leaves-watercolour', 'gypsophila-save-the-date', 'kraft', 'lavender', 'movie', 'mr-mr', 'mushroom', 'october', 'old-sunflowers', 'olive', 'outlines', 'rust', 'whimsical')
  LOOP
    INSERT INTO collection_products (collection_id, design_template_id, status, is_live, committed_at)
    VALUES (coll.id, std_template_id, 'complete', true, now())
    ON CONFLICT (collection_id, design_template_id) DO UPDATE SET status = 'complete', is_live = true, committed_at = now()
    RETURNING id INTO cp_id;

    p_slug := coll.slug || '-save-the-date';
    p_name := coll.name || ' Save the Date';

    INSERT INTO products (design_collection_id, product_type_id, name, slug, description, base_price, is_published, mockup_images)
    VALUES (coll.id, pt_id, p_name, p_slug,
      'collection_product:' || cp_id,
      1.50, true,
      ARRAY['/designs/' || coll.slug || '/product.png', '/designs/' || coll.slug || '/thumbnail.png'])
    ON CONFLICT (slug) DO UPDATE SET
      name = EXCLUDED.name, is_published = true, mockup_images = EXCLUDED.mockup_images;
  END LOOP;
END $$;